# Generated by Django 4.2.7 on 2023-11-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('image', models.URLField(verbose_name='image')),
                ('release_date', models.DateField(verbose_name='release_date')),
                ('lte_exists', models.BooleanField(verbose_name='lte_exists')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
    ]
